In [42]:
import pandas as pd

df = pd.read_csv(
    "/content/drive/MyDrive/Projects/IGEM Summer 2026/Therapeutic Antibody Humanization Prediction /ERR220444_Heavy_Bulk.csv.gz",
    compression="gzip",
    skiprows=1
)

print(df.shape)
df.head()

(13379, 97)

,sequence,locus,stop_codon,vj_in_frame,v_frameshift,productive,rev_comp,complete_vdj,v_call,d_call,...,cdr3_start,cdr3_end,np1,np1_length,np2,np2_length,c_region,Redundancy,ANARCI_numbering,ANARCI_status
0,GGCCTCAGTGAAGGTCTCCTGCAAGGCTTCTGGATTCACCTTTAGT...,H,F,T,F,T,F,F,IGHV1-58*01,IGHD3-3*01,...,245.0,289.0,CAC,3.0,CGGACTAC,8.0,NCGTGCCNCTCTCAGAGAGTACAGAGNGTCGGCGGCTCTCAAGGAC...,1,"{'fwh1': {'18 ': 'S', '19 ': 'V', '20 ': 'K', ...","|Deletions: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,..."
1,GGCCTCAGTGAAGGTCTCCTGCAAGGCTTCTGGATTCACCTTTACT...,H,F,T,F,T,F,F,IGHV1-58*01,IGHD3-22*01,...,245.0,292.0,TTCCGGC,7.0,A,1.0,GGTAAGAGTACAGGAGTGGTCGGCGTCTCTCAAGGGGCACACAGGG...,1,"{'fwh1': {'18 ': 'S', '19 ': 'V', '20 ': 'K', ...","|Deletions: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,..."
2,GGCCTCAGTGAAGGTCTCCTGCAAGGCTTCTGGATTCACCTTTACT...,H,F,T,F,T,F,F,IGHV1-58*01,IGHD1-26*01,...,245.0,283.0,T,1.0,CT,2.0,GTAAGAGTACAGGAGTGGTCGGCGTCTCTCAAGGGCACACAGGGGG...,2,"{'fwh1': {'18 ': 'S', '19 ': 'V', '20 ': 'K', ...","|Deletions: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,..."
3,GGCCTCAGTGAAGGTCTCCTGCAAGGCTTCTGGAGGCACCTTCAGC...,H,F,T,F,T,F,F,IGHV1-8*02,IGHD3-10*01,...,245.0,304.0,CCCAC,5.0,GAT,3.0,GGTAAGAGTACAGGGAGTGGGTCGGGGCGGTCTCTCAAAGGGCACA...,1,"{'fwh1': {'18 ': 'S', '19 ': 'V', '20 ': 'K', ...","|Deletions: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,..."
4,NNCCCCTATTCCCCCTGTGTGCCCTTGAGAGACGCCCGACCACTCC...,H,F,T,F,T,T,F,IGHV1-8*01,IGHD2-2*01,...,297.0,326.0,C,1.0,CGGCCGA,7.0,GTAAG,1,"{'fwh1': {'18 ': 'S', '19 ': 'V', '20 ': 'K', ...","|Deletions: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,..."

In [43]:
print(df.columns)

Index(['sequence', 'locus', 'stop_codon', 'vj_in_frame', 'v_frameshift',
       'productive', 'rev_comp', 'complete_vdj', 'v_call', 'd_call', 'j_call',
       'sequence_alignment', 'germline_alignment', 'sequence_alignment_aa',
       'germline_alignment_aa', 'v_alignment_start', 'v_alignment_end',
       'd_alignment_start', 'd_alignment_end', 'j_alignment_start',
       'j_alignment_end', 'v_sequence_alignment', 'v_sequence_alignment_aa',
       'v_germline_alignment', 'v_germline_alignment_aa',
       'd_sequence_alignment', 'd_sequence_alignment_aa',
       'd_germline_alignment', 'd_germline_alignment_aa',
       'j_sequence_alignment', 'j_sequence_alignment_aa',
       'j_germline_alignment', 'j_germline_alignment_aa', 'fwr1', 'fwr1_aa',
       'cdr1', 'cdr1_aa', 'fwr2', 'fwr2_aa', 'cdr2', 'cdr2_aa', 'fwr3',
       'fwr3_aa', 'fwr4', 'fwr4_aa', 'cdr3', 'cdr3_aa', 'junction',
       'junction_length', 'junction_aa', 'junction_aa_length', 'v_score',
       'd_score', 'j_score', 'v_cigar', 'd_cigar', 'j_cigar', 'v_support',
       'd_support', 'j_support', 'v_identity', 'd_identity', 'j_identity',
       'v_sequence_start', 'v_sequence_end', 'v_germline_start',
       'v_germline_end', 'd_sequence_start', 'd_sequence_end',
       'd_germline_start', 'd_germline_end', 'j_sequence_start',
       'j_sequence_end', 'j_germline_start', 'j_germline_end', 'fwr1_start',
       'fwr1_end', 'cdr1_start', 'cdr1_end', 'fwr2_start', 'fwr2_end',
       'cdr2_start', 'cdr2_end', 'fwr3_start', 'fwr3_end', 'fwr4_start',
       'fwr4_end', 'cdr3_start', 'cdr3_end', 'np1', 'np1_length', 'np2',
       'np2_length', 'c_region', 'Redundancy', 'ANARCI_numbering',
       'ANARCI_status'],
      dtype='object')

In [44]:
human_df = df[["sequence_alignment_aa"]].copy()

human_df.rename(
    columns={"sequence_alignment_aa": "sequence"},
    inplace=True
)

human_df["label"] = 1
human_df["species"] = "human"

human_df.head()

                                            sequence  label species
0  SVKVSCKASGFTFSRSAVQWVRQARGQCLEWIGWIVVGSGNTNYAQ...      1   human
1  SVKVSCKASGFTFTSSAVQWVRQARGQRLEWIGWIVVGSDNTNYAQ...      1   human
2  SVKVSCKASGFTFTSSAVQWVRQARGQRLEWIGWIVVGSGNTNYAQ...      1   human
3  ASVKVSCKASGGTFSSYAISWVRQATGQGLEWMGWMNPNSGNTGYA...      1   human
4  ASVKVSCKASGYTFTSYDINWVRQATGQGLEWMGWMNPNSGNTGYA...      1   human

In [45]:
human_df = human_df.dropna()

human_df = human_df[
    ~human_df["sequence"].str.contains("X", na=False)
]

human_df.head()

                                            sequence  label species
0  SVKVSCKASGFTFSRSAVQWVRQARGQCLEWIGWIVVGSGNTNYAQ...      1   human
1  SVKVSCKASGFTFTSSAVQWVRQARGQRLEWIGWIVVGSDNTNYAQ...      1   human
2  SVKVSCKASGFTFTSSAVQWVRQARGQRLEWIGWIVVGSGNTNYAQ...      1   human
3  ASVKVSCKASGGTFSSYAISWVRQATGQGLEWMGWMNPNSGNTGYA...      1   human
4  ASVKVSCKASGYTFTSYDINWVRQATGQGLEWMGWMNPNSGNTGYA...      1   human

In [46]:
print("Human sequences:", len(human_df))

Human sequences: 13240

In [47]:
print(df.shape)

print("Human sequences:", len(human_df))

human_df.head()

(13379, 97)
Human sequences: 13240

                                            sequence  label species
0  SVKVSCKASGFTFSRSAVQWVRQARGQCLEWIGWIVVGSGNTNYAQ...      1   human
1  SVKVSCKASGFTFTSSAVQWVRQARGQRLEWIGWIVVGSDNTNYAQ...      1   human
2  SVKVSCKASGFTFTSSAVQWVRQARGQRLEWIGWIVVGSGNTNYAQ...      1   human
3  ASVKVSCKASGGTFSSYAISWVRQATGQGLEWMGWMNPNSGNTGYA...      1   human
4  ASVKVSCKASGYTFTSYDINWVRQATGQGLEWMGWMNPNSGNTGYA...      1   human

In [48]:
import pandas as pd

mouse_df = pd.read_csv(
    "/content/drive/MyDrive/Projects/IGEM Summer 2026/Therapeutic Antibody Humanization Prediction /ERR1759659_1_Heavy_Bulk.csv.gz",
    compression="gzip",
    skiprows=1
)

mouse_df = mouse_df[["sequence_alignment_aa"]].copy()

mouse_df.rename(
    columns={"sequence_alignment_aa":"sequence"},
    inplace=True
)

mouse_df["label"] = 0
mouse_df["species"] = "mouse"

mouse_df = mouse_df.dropna()

mouse_df = mouse_df[
    ~mouse_df["sequence"].str.contains("X", na=False)
]

print(len(mouse_df))

5896

In [49]:
import pandas as pd

rat_df = pd.read_csv(
    "/content/drive/MyDrive/Projects/IGEM Summer 2026/Therapeutic Antibody Humanization Prediction /SRR5534360_Heavy_Bulk.csv.gz",
    compression="gzip",
    skiprows=1
)

rat_df = rat_df[["sequence_alignment_aa"]].copy()

rat_df.rename(
    columns={"sequence_alignment_aa":"sequence"},
    inplace=True
)

rat_df["label"] = 0
rat_df["species"] = "rat"

rat_df = rat_df.dropna()

rat_df = rat_df[
    ~rat_df["sequence"].str.contains("X", na=False)
]

print(len(rat_df))

3484

In [50]:
import pandas as pd

camel_df = pd.read_csv(
    "/content/drive/MyDrive/Projects/IGEM Summer 2026/Therapeutic Antibody Humanization Prediction /SRR3544217_1_Heavy_Bulk.csv.gz",
    compression="gzip",
    skiprows=1
)

camel_df = camel_df[["sequence_alignment_aa"]].copy()

camel_df.rename(
    columns={"sequence_alignment_aa":"sequence"},
    inplace=True
)

camel_df["label"] = 0
camel_df["species"] = "camel"

camel_df = camel_df.dropna()

camel_df = camel_df[
    ~camel_df["sequence"].str.contains("X", na=False)
]

print(len(camel_df))

6420

In [51]:
print(len(human_df))
print(len(mouse_df))
print(len(rat_df))
print(len(camel_df))

13240
5896
3484
6420

In [52]:
#Combined Dataset
combined_df = pd.concat([
    human_df,
    mouse_df,
    rat_df,
    camel_df
], ignore_index=True)

print(combined_df.shape)

(29040, 3)

In [53]:
#Remove Duplicates
before = len(combined_df)

combined_df = combined_df.drop_duplicates(
    subset="sequence"
)

after = len(combined_df)

print("Before:", before)
print("After:", after)
print("Removed:", before-after)

Before: 29040
After: 29040
Removed: 0

In [54]:
combined_df["label"].value_counts()

label
0    15800
1    13240
Name: count, dtype: int64

In [55]:
combined_df.to_csv(
    "antibody_humanization_dataset.csv",
    index=False
)

In [56]:
import re

valid_aa = set("ACDEFGHIKLMNPQRSTVWY")

def is_valid(seq):
    return set(seq).issubset(valid_aa)

combined_df = combined_df[
    combined_df["sequence"].apply(is_valid)
]

print(len(combined_df))

29040

In [57]:
combined_df["length"] = combined_df["sequence"].str.len()

print(combined_df["length"].describe())

count    29040.000000
mean       113.527135
std          7.656830
min         48.000000
25%        108.000000
50%        114.000000
75%        119.000000
max        153.000000
Name: length, dtype: float64

In [58]:
combined_df.groupby("species")["length"].describe()

           count        mean       std   min    25%    50%    75%    max
species
camel     6420.0  119.217134  7.736099  55.0  116.0  120.0  124.0  153.0
human    13240.0  108.256647  5.966824  48.0  105.0  108.0  112.0  128.0
mouse     5896.0  116.803087  3.948962  71.0  115.0  117.0  119.0  133.0
rat       3484.0  117.527268  4.163484  66.0  117.0  119.0  120.0  141.0

In [59]:
#Cleaning <80 aa seq
combined_df = combined_df[
    combined_df["length"] >= 80
]

print(combined_df.shape)
print(combined_df["label"].value_counts())

(28917, 4)
label
0    15768
1    13149
Name: count, dtype: int64

In [60]:
combined_df.to_csv(
    "antibody_humanization_dataset_clean.csv",
    index=False
)

### FEATURE ENGINNERING

In [61]:
from collections import Counter

amino_acids = list("ACDEFGHIKLMNPQRSTVWY")

def aa_composition(seq):
    counts = Counter(seq)
    length = len(seq)

    return {
        aa: counts.get(aa, 0)/length
        for aa in amino_acids
    }

In [62]:
features = pd.DataFrame(
    combined_df["sequence"]
    .apply(aa_composition)
    .tolist()
)

features["length"] = (
    combined_df["sequence"].str.len()
)

print(features.shape)

(28917, 21)

In [63]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    features,
    combined_df["label"],
    test_size=0.2,
    random_state=42,
    stratify=combined_df["label"]
)

In [64]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, n_jobs=-1, random_state=42)

In [65]:
from sklearn.metrics import (
    accuracy_score,
    classification_report
)

pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

Accuracy: 0.9892807745504841
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      3154
           1       0.99      0.98      0.99      2630

    accuracy                           0.99      5784
   macro avg       0.99      0.99      0.99      5784
weighted avg       0.99      0.99      0.99      5784

In [66]:
print(features.shape)
print("Accuracy:", accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

(28917, 21)
Accuracy: 0.9892807745504841
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      3154
           1       0.99      0.98      0.99      2630

    accuracy                           0.99      5784
   macro avg       0.99      0.99      0.99      5784
weighted avg       0.99      0.99      0.99      5784

For a simple feature set:

20 amino acid frequencies + length

getting:

Accuracy = 99.1%

is unusually high.

This usually means one of three things:

Possibility 1 (Most Likely): Species Bias

Your non-human class is:

Mouse
Rat
Camel

Camel antibodies (VHH/nanobodies) have distinctive sequence characteristics compared to human antibodies.

The model may be learning:

"Is this camel?" rather than "Is this humanized?"

Possibility 2: Dataset Leakage

We need to check whether nearly identical sequences appear in both train and test sets.

Because we split after combining sequences, related clonotypes can end up in both sets.

Possibility 3: Real Biological Signal

Human and rodent germline repertoires are genuinely different.

But 99% with only amino-acid composition is still surprisingly high.

In [67]:
import pandas as pd

importance = pd.DataFrame({
    "feature": features.columns,
    "importance": model.feature_importances_
})

importance = importance.sort_values(
    "importance",
    ascending=False
)

print(importance.head(15))

   feature  importance
20  length    0.231867
18       W    0.135481
3        E    0.119202
13       Q    0.098251
1        C    0.080695
9        L    0.062557
8        K    0.042607
12       P    0.029877
10       M    0.026280
7        I    0.025875
19       Y    0.022068
16       T    0.021710
15       S    0.021620
5        G    0.018915
11       N    0.014962

In [68]:
combined_df.groupby("species")["length"].describe()

           count        mean       std   min    25%    50%    75%    max
species
camel     6390.0  119.451017  6.938883  81.0  116.0  120.0  124.0  153.0
human    13149.0  108.533957  4.917328  80.0  105.0  108.0  112.0  128.0
mouse     5895.0  116.810857  3.903965  80.0  115.0  117.0  119.0  133.0
rat       3483.0  117.542061  4.071468  83.0  117.0  119.0  120.0  141.0

In [69]:
X_no_length = features.drop(columns=["length"])

In [70]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

X_train, X_test, y_train, y_test = train_test_split(
    X_no_length,
    combined_df["label"],
    test_size=0.2,
    random_state=42,
    stratify=combined_df["label"]
)

model2 = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

model2.fit(X_train, y_train)

pred2 = model2.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred2))
print(classification_report(y_test, pred2))

Accuracy: 0.9823651452282157
              precision    recall  f1-score   support

           0       0.98      0.99      0.98      3154
           1       0.98      0.98      0.98      2630

    accuracy                           0.98      5784
   macro avg       0.98      0.98      0.98      5784
weighted avg       0.98      0.98      0.98      5784

In [71]:
X_with_length = features.copy()

X_without_length = features.drop(
    columns=["length"]
)

In [72]:
from sklearn.model_selection import train_test_split

train_idx, test_idx = train_test_split(
    combined_df.index,
    test_size=0.2,
    random_state=42,
    stratify=combined_df["label"]
)

### Germline Checking

In [74]:
dir()

['Counter',
 'In',
 'Out',
 'RandomForestClassifier',
 'X_no_length',
 'X_test',
 'X_train',
 'X_with_length',
 'X_without_length',
 '_',
 '_1',
 '_19',
 '_23',
 '_30',
 '_34',
 '_35',
 '_36',
 '_37',
 '_4',
 '_42',
 '_44',
 '_45',
 '_47',
 '_54',
 '_58',
 '_6',
 '_64',
 '_68',
 '_7',
 '_9',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i14',
 '_i15',
 '_i16',
 '_i17',
 '_i18',
 '_i19',
 '_i2',
 '_i20',
 '_i21',
 '_i22',
 '_i23',
 '_i24',
 '_i25',
 '_i26',
 '_i27',
 '_i28',
 '_i29',
 '_i3',
 '_i30',
 '_i31',
 '_i32',
 '_i33',
 '_i34',
 '_i35',
 '_i36',
 '_i37',
 '_i38',
 '_i39',
 '_i4',
 '_i40',
 '_i41',
 '_i42',
 '_i43',
 '_i44',
 '_i45',
 '_i46',
 '_i47',
 '_i48',
 '_i49',
 '_i5',
 '_i50',
 '_i51',
 '_i52',
 '_i53',
 '_i54',
 '_i55',
 '_i56',
 '_i57',
 '_i58',
 '_i59',
 '_i6',
 '_i60',
 '_i61',
 '_i62',
 '_i63',
 '_i64',
 '_i65',
 '_i66',
 '_i67',
 '_i68',
 '_i69',
 '_i7',
 '_i70',
 '_i71',
 '_i72',
 '_i73',
 '_i74',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'aa_composition',
 'accuracy_score',
 'after',
 'amino_acids',
 'before',
 'camel_df',
 'classification_report',
 'combined_df',
 'df',
 'exit',
 'f',
 'features',
 'get_ipython',
 'gzip',
 'human_df',
 'i',
 'importance',
 'is_valid',
 'model',
 'model2',
 'mouse_df',
 'pd',
 'pred',
 'pred2',
 'quit',
 'rabbit_df',
 'rat_df',
 're',
 'test_idx',
 'train_idx',
 'train_test_split',
 'valid_aa',
 'y_test',
 'y_train']

### Human-Likeness Scoring

In [75]:
proba = model2.predict_proba(X_test)

print(proba[:5])

[[1.    0.   ]
 [1.    0.   ]
 [0.98  0.02 ]
 [0.985 0.015]
 [0.015 0.985]]

In [76]:
scores = proba[:,1] * 100

In [78]:
print(scores[:10])

[  0.    0.    2.    1.5  98.5  98.    0.    0.  100.    1. ]

In [79]:
def human_category(score):
    if score >= 90:
        return "Highly Human-Like"
    elif score >= 70:
        return "Moderately Human-Like"
    elif score >= 40:
        return "Partially Humanized"
    else:
        return "Non-Human"

In [80]:
results = pd.DataFrame({
    "score": scores
})

results["category"] = results["score"].apply(
    human_category
)

print(results.head(20))

    score               category
0     0.0              Non-Human
1     0.0              Non-Human
2     2.0              Non-Human
3     1.5              Non-Human
4    98.5      Highly Human-Like
5    98.0      Highly Human-Like
6     0.0              Non-Human
7     0.0              Non-Human
8   100.0      Highly Human-Like
9     1.0              Non-Human
10    5.5              Non-Human
11    0.5              Non-Human
12  100.0      Highly Human-Like
13   75.5  Moderately Human-Like
14   23.0              Non-Human
15   14.5              Non-Human
16   95.5      Highly Human-Like
17    2.5              Non-Human
18    0.0              Non-Human
19  100.0      Highly Human-Like

In [83]:
proba = model2.predict_proba(X_test)

scores = proba[:,1] * 100

print(scores[:20])

[  0.    0.    2.    1.5  98.5  98.    0.    0.  100.    1.    5.5   0.5
 100.   75.5  23.   14.5  95.5   2.5   0.  100. ]

In [85]:
from collections import Counter

amino_acids = list("ACDEFGHIKLMNPQRSTVWY")

def sequence_to_features(seq):
    counts = Counter(seq)
    length = len(seq)

    features = {
        aa: counts.get(aa, 0)/length
        for aa in amino_acids
    }

    return features

In [86]:
import pandas as pd

def analyze_antibody(sequence):

    feat = pd.DataFrame(
        [sequence_to_features(sequence)]
    )

    prob = model2.predict_proba(feat)[0][1]

    score = prob * 100

    if score >= 90:
        category = "Highly Human-Like"

    elif score >= 70:
        category = "Moderately Human-Like"

    elif score >= 40:
        category = "Partially Humanized"

    else:
        category = "Non-Human"

    return {
        "score": round(score,2),
        "category": category
    }

In [87]:
sample = combined_df.iloc[0]["sequence"]

print(
    analyze_antibody(sample)
)

{'score': np.float64(74.5), 'category': 'Moderately Human-Like'}

In [88]:
demo = combined_df.sample(
    20,
    random_state=42
)

In [90]:
demo_features = pd.DataFrame(
    demo["sequence"].apply(aa_composition).tolist()
)

demo_features = demo_features[X_no_length.columns]

demo["human_score"] = (
    model2.predict_proba(demo_features)[:,1] * 100
)

demo[
    ["species","human_score"]
].head()

      species  human_score
14187   mouse          0.5
1408    human         94.5
17011   mouse          0.0
12319   human         98.5
28108   camel          1.0

In [91]:
sample = combined_df.iloc[0]["sequence"]

print(
    analyze_antibody(sample)
)

{'score': np.float64(74.5), 'category': 'Moderately Human-Like'}

In [93]:
demo = combined_df.sample(
    20,
    random_state=42
)

demo_features = pd.DataFrame(
    demo["sequence"].apply(aa_composition).tolist()
)

demo_features = demo_features[X_no_length.columns]

demo["human_score"] = (
    model2.predict_proba(demo_features)[:,1] * 100
)

print(
    demo[
        ["species","human_score"]
    ]
)

      species  human_score
14187   mouse          0.5
1408    human         94.5
17011   mouse          0.0
12319   human         98.5
28108   camel          1.0
20691     rat          0.0
10963   human        100.0
3057    human         99.0
24347   camel          0.0
15771   mouse          0.0
8200    human         98.0
17322   mouse          0.0
16035   mouse          0.5
29025   camel          0.0
10584   human         97.5
11645   human         97.0
12859   human        100.0
27784   camel         12.0
15350   mouse          0.0
24550   camel          0.0

# ==========================
# Antibody Analyzer Module
# ==========================

In [94]:
from collections import Counter
import pandas as pd

amino_acids = list("ACDEFGHIKLMNPQRSTVWY")

def sequence_to_features(seq):

    seq = seq.upper().strip()

    counts = Counter(seq)
    length = len(seq)

    features = {
        aa: counts.get(aa, 0) / length
        for aa in amino_acids
    }

    return pd.DataFrame([features])

In [95]:
def get_category(score):

    if score >= 90:
        return "Highly Human-Like"

    elif score >= 70:
        return "Moderately Human-Like"

    elif score >= 40:
        return "Partially Humanized"

    else:
        return "Non-Human"

In [96]:
def get_confidence(score):

    distance = abs(score - 50)

    if distance >= 40:
        return "Very High"

    elif distance >= 25:
        return "High"

    elif distance >= 10:
        return "Moderate"

    return "Low"

In [97]:
def analyze_antibody(sequence):

    feat = sequence_to_features(sequence)

    prob = model2.predict_proba(feat)[0][1]

    score = round(prob * 100, 2)

    return {
        "Human-Likeness Score": score,
        "Category": get_category(score),
        "Confidence": get_confidence(score)
    }

In [98]:
human_seq = combined_df[
    combined_df["species"] == "human"
].iloc[0]["sequence"]

print(
    analyze_antibody(human_seq)
)

{'Human-Likeness Score': np.float64(74.5), 'Category': 'Moderately Human-Like', 'Confidence': 'Moderate'}

In [99]:
mouse_seq = combined_df[
    combined_df["species"] == "mouse"
].iloc[0]["sequence"]

print(
    analyze_antibody(mouse_seq)
)

{'Human-Likeness Score': np.float64(0.0), 'Category': 'Non-Human', 'Confidence': 'Very High'}

Upgrade 2: Explainability Layer

In [100]:
importance = pd.DataFrame({
    "feature": X_no_length.columns,
    "importance": model2.feature_importances_
})

importance = importance.sort_values(
    "importance",
    ascending=False
)

In [101]:
top_features = (
    importance["feature"]
    .head(10)
    .tolist()
)

print(top_features)

['W', 'E', 'Q', 'C', 'L', 'K', 'M', 'P', 'I', 'T']

In [102]:
def explain_sequence(sequence):

    feat = sequence_to_features(sequence)

    explanations = []

    for feature in top_features[:5]:

        value = feat.iloc[0][feature]

        explanations.append(
            f"{feature}: {round(value,4)}"
        )

    return explanations

In [109]:
def analyze_antibody(sequence):

    valid, msg = validate_sequence(sequence)

    if not valid:
        return {
            "Error": msg
        }

    feat = sequence_to_features(sequence)

    prob = model2.predict_proba(feat)[0][1]

    score = round(prob * 100, 2)

    return {
        "Human-Likeness Score": score,
        "Category": get_category(score),
        "Confidence": get_confidence(score),
        "Feature Summary":
            explain_sequence(sequence)
    }

In [125]:
print(analyze_antibody(human_seq))

{'Human-Likeness Score': np.float64(74.5), 'Category': 'Moderately Human-Like', 'Confidence': 'Moderate', 'Feature Summary': ['W: 0.04', 'E: 0.05', 'Q: 0.05', 'C: 0.03', 'L: 0.09']}

In [126]:
print(analyze_antibody(mouse_seq))

{'Human-Likeness Score': np.float64(0.0), 'Category': 'Non-Human', 'Confidence': 'Very High', 'Feature Summary': ['W: 0.0252', 'E: 0.0252', 'Q: 0.0672', 'C: 0.0336', 'L: 0.0588']}

In [127]:
# Demonstrate with an invalid sequence (too short)
print(analyze_antibody("ABC"))

{'Error': 'Sequence too short'}

In [128]:
# Demonstrate with an invalid sequence (contains 'X')
print(analyze_antibody("ACDEFGHIKLMNPQRSTVWXACDEFGHIKLMNPQRSTVWXACDEFGHIKLMNPQRSTVWXACDEFGHIKLMNPQRSTVWX"))

{'Error': 'Invalid amino acids'}

In [104]:
print(
    analyze_antibody(human_seq)
)

{'Human-Likeness Score': np.float64(74.5), 'Category': 'Moderately Human-Like', 'Confidence': 'Moderate', 'Feature Summary': ['W: 0.04', 'E: 0.05', 'Q: 0.05', 'C: 0.03', 'L: 0.09']}

Upgrade 3: Validation Layer

In [108]:
VALID_AA = set(amino_acids)

def validate_sequence(seq):

    seq = seq.upper().strip()

    if len(seq) < 80:
        return False, "Sequence too short"

    if not set(seq).issubset(
        VALID_AA
    ):
        return False, "Invalid amino acids"

    return True, "Valid"

Upgrade 4 Mutation Simulation Engine

In [110]:
def mutate_sequence(seq, position, new_aa):

    seq = list(seq)

    seq[position] = new_aa

    return "".join(seq)

In [111]:
mutate_sequence(
    "ACDEFG",
    2,
    "W"
)

'ACWEFG'

In [112]:
def get_score(sequence):

    feat = sequence_to_features(sequence)

    prob = model2.predict_proba(feat)[0][1]

    return prob * 100

In [113]:
AMINO_ACIDS = list(
    "ACDEFGHIKLMNPQRSTVWY"
)

In [114]:
def best_single_mutations(
    sequence,
    top_n=10
):

    original_score = get_score(sequence)

    candidates = []

    for pos in range(len(sequence)):

        original_aa = sequence[pos]

        for aa in AMINO_ACIDS:

            if aa == original_aa:
                continue

            mutated = mutate_sequence(
                sequence,
                pos,
                aa
            )

            score = get_score(mutated)

            improvement = (
                score -
                original_score
            )

            if improvement > 0:

                candidates.append({

                    "position":
                        pos + 1,

                    "mutation":
                        f"{original_aa}{pos+1}{aa}",

                    "new_score":
                        round(score,2),

                    "gain":
                        round(improvement,2)
                })

    candidates = sorted(
        candidates,
        key=lambda x: x["gain"],
        reverse=True
    )

    return candidates[:top_n]

In [116]:
mouse_seq = combined_df[
    combined_df["species"]=="mouse"].iloc[0]["sequence"]

In [117]:
results = best_single_mutations(
    mouse_seq,
    top_n=10
)

results[:10]

[{'position': 10,
  'mutation': 'E10R',
  'new_score': np.float64(6.0),
  'gain': np.float64(6.0)},
 {'position': 46,
  'mutation': 'E46R',
  'new_score': np.float64(6.0),
  'gain': np.float64(6.0)},
 {'position': 89,
  'mutation': 'E89R',
  'new_score': np.float64(6.0),
  'gain': np.float64(6.0)},
 {'position': 10,
  'mutation': 'E10C',
  'new_score': np.float64(5.0),
  'gain': np.float64(5.0)},
 {'position': 10,
  'mutation': 'E10Y',
  'new_score': np.float64(5.0),
  'gain': np.float64(5.0)},
 {'position': 46,
  'mutation': 'E46C',
  'new_score': np.float64(5.0),
  'gain': np.float64(5.0)},
 {'position': 46,
  'mutation': 'E46Y',
  'new_score': np.float64(5.0),
  'gain': np.float64(5.0)},
 {'position': 89,
  'mutation': 'E89C',
  'new_score': np.float64(5.0),
  'gain': np.float64(5.0)},
 {'position': 89,
  'mutation': 'E89Y',
  'new_score': np.float64(5.0),
  'gain': np.float64(5.0)},
 {'position': 10,
  'mutation': 'E10A',
  'new_score': np.float64(4.0),
  'gain': np.float64(4.0)}]

Upgrade 5 — Humanization Report

In [118]:
results = best_single_mutations(
    mouse_seq,
    top_n=10
)

results

[{'position': 10,
  'mutation': 'E10R',
  'new_score': np.float64(6.0),
  'gain': np.float64(6.0)},
 {'position': 46,
  'mutation': 'E46R',
  'new_score': np.float64(6.0),
  'gain': np.float64(6.0)},
 {'position': 89,
  'mutation': 'E89R',
  'new_score': np.float64(6.0),
  'gain': np.float64(6.0)},
 {'position': 10,
  'mutation': 'E10C',
  'new_score': np.float64(5.0),
  'gain': np.float64(5.0)},
 {'position': 10,
  'mutation': 'E10Y',
  'new_score': np.float64(5.0),
  'gain': np.float64(5.0)},
 {'position': 46,
  'mutation': 'E46C',
  'new_score': np.float64(5.0),
  'gain': np.float64(5.0)},
 {'position': 46,
  'mutation': 'E46Y',
  'new_score': np.float64(5.0),
  'gain': np.float64(5.0)},
 {'position': 89,
  'mutation': 'E89C',
  'new_score': np.float64(5.0),
  'gain': np.float64(5.0)},
 {'position': 89,
  'mutation': 'E89Y',
  'new_score': np.float64(5.0),
  'gain': np.float64(5.0)},
 {'position': 10,
  'mutation': 'E10A',
  'new_score': np.float64(4.0),
  'gain': np.float64(4.0)}]

Upgrade 5: Position-Aware Features

In [121]:
import joblib

joblib.dump(
    model2,
    "model.pkl"
)

['model.pkl']

Upgrade 7: Save the Whole Pipeline

In [ ]:
pipeline = {
    "model": model2,
    "feature_names": list(X_no_length.columns)
}

In [ ]:
joblib.dump(
    pipeline,
    "antibody_predictor_pipeline.pkl"
)

re